import assert from "node:assert/strict";
import test from "node:test";
import { webcrypto } from "node:crypto";
import { readFile } from "node:fs/promises";
if(!globalThis.crypto)Object.defineProperty(globalThis,"crypto",{value:webcrypto});
const {onRequestPost:submit}=await import("../functions/api/feedback.js");
const {onRequestGet:read}=await import("../functions/owner/api/feedback.js");

function db({limit=false}={}){const rows=[],calls=[];return{rows,calls,prepare(sql){const call={sql,args:[]};calls.push(call);const statement={bind(...args){call.args=args;return statement},async first(){if(sql.includes("FROM owner_feedback"))return rows.find(row=>row.request_id===call.args[0])||null;throw new Error("Unexpected first")},async all(){if(sql.includes("FROM owner_feedback"))return{results:[...rows].reverse()};throw new Error("Unexpected all")},async run(){return{success:true}},async execute(){if(sql.startsWith("INSERT INTO feedback_ingest_windows"))return limit?null:{count:1};if(sql.startsWith("INSERT INTO owner_feedback")){if(rows.some(row=>row.request_id===call.args[1]))return null;const row={feedback_id:call.args[0],request_id:call.args[1],message:call.args[2],name:call.args[3],page:call.args[4],happened:call.args[5],expected:call.args[6],reproduction:call.args[7],context:call.args[8],created_at:call.args[9]};rows.push(row);return{feedback_id:row.feedback_id,created_at:row.created_at}}throw new Error("Unexpected execute")},async batchRun(){return{results:[await statement.execute()].filter(Boolean)}}};return statement},async batch(statements){const results=[];for(const statement of statements)results.push(await statement.batchRun());return results}}}
const valid={requestId:"11111111-1111-4111-8111-111111111111",message:"Synthetic QA feedback only.",name:"",page:"Scribble preview",happened:"A preview action was tested.",expected:"A private confirmation.",reproduction:"Open preview and submit synthetic text."};
function request(body=valid,headers={}){return new Request("https://preview.example/api/feedback",{method:"POST",headers:{origin:"https://preview.example","sec-fetch-site":"same-origin","content-type":"application/json",...headers},body:typeof body==="string"?body:JSON.stringify(body)})}
function env(database,overrides={}){return{ANALYTICS_QUERY_CONTEXT:"test",TRIKZIK_DB:database,...overrides}}

test("preview feedback accepts bounded plain text once and retries idempotently",async()=>{const database=db();const first=await submit({request:request(),env:env(database)});assert.equal(first.status,200);assert.equal((await first.json()).repeated,false);const retry=await submit({request:request(),env:env(database)});assert.equal(retry.status,200);assert.equal((await retry.json()).repeated,true);assert.equal(database.rows.length,1);assert.equal(database.rows[0].context,"test")});
test("feedback fails closed outside preview and rejects cross-site, shape, type, size, and quota violations",async()=>{assert.equal((await submit({request:request(),env:env(db(),{TRIKZIK_DB:null})})).status,404);assert.equal((await submit({request:request(),env:env(db(),{ANALYTICS_QUERY_CONTEXT:"production"})})).status,404);assert.equal((await submit({request:request(valid,{origin:"https://evil.example"}),env:env(db())})).status,403);assert.equal((await submit({request:request(valid,{"content-type":"text/plain"}),env:env(db())})).status,415);assert.equal((await submit({request:request({...valid,extra:true}),env:env(db())})).status,400);assert.equal((await submit({request:request({...valid,message:"x".repeat(2001)}),env:env(db())})).status,400);assert.equal((await submit({request:request("x".repeat(8200)),env:env(db())})).status,413);assert.equal((await submit({request:request(),env:env(db({limit:true}))})).status,429)});

function b64(value){return Buffer.from(value).toString("base64url")}
async function ownerFixture(){const pair=await crypto.subtle.generateKey({name:"RSASSA-PKCS1-v1_5",modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:"SHA-256"},true,["sign","verify"]),jwk=await crypto.subtle.exportKey("jwk",pair.publicKey);Object.assign(jwk,{kid:"feedback-key",alg:"RS256",use:"sig"});const now=Math.floor(Date.now()/1000),header=b64(JSON.stringify({alg:"RS256",kid:jwk.kid})),claims=b64(JSON.stringify({aud:"trikzik-owner-auth",iss:"https://securetoken.google.com/trikzik-owner-auth",sub:"owner-uid",user_id:"owner-uid",email:"owner@example.test",email_verified:true,iat:now-10,auth_time:now-20,exp:now+300})),signature=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",pair.privateKey,new TextEncoder().encode(`${header}.${claims}`));return{token:`${header}.${claims}.${b64(signature)}`,fetch:async()=>new Response(JSON.stringify({keys:[jwk]}),{status:200})}}
test("feedback remains private behind the exact owner gate",async()=>{const database=db();database.rows.push({feedback_id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",request_id:valid.requestId,...valid,context:"test",created_at:Math.floor(Date.now()/1000)});const base={ANALYTICS_DASHBOARD_ENABLED:"true",ANALYTICS_QUERY_CONTEXT:"test",ANALYTICS_OWNER_HOSTS:"preview.example",FIREBASE_PROJECT_ID:"trikzik-owner-auth",FIREBASE_OWNER_EMAIL:"owner@example.test",FIREBASE_OWNER_UID:"owner-uid",TRIKZIK_DB:database},url="https://preview.example/owner/api/feedback";assert.equal((await read({request:new Request(url,{headers:{origin:"https://preview.example","sec-fetch-site":"same-origin"}}),env:base})).status,401);const fixture=await ownerFixture(),original=globalThis.fetch;globalThis.fetch=fixture.fetch;try{const response=await read({request:new Request(url,{headers:{authorization:`Bearer ${fixture.token}`,origin:"https://preview.example","sec-fetch-site":"same-origin"}}),env:base});assert.equal(response.status,200);const data=await response.json();assert.equal(data.entries.length,1);assert.equal(data.entries[0].message,valid.message);assert.equal(data.retention.automaticDeletion,false)}finally{globalThis.fetch=original}});
test("feedback page keeps optional details collapsed and preserves failed drafts until server confirmation",async()=>{const page=await readFile(new URL("../feedback.html",import.meta.url),"utf8");for(const value of ["What would you like to tell me?","Name <span>Optional","Add useful details","What happened?","What did you expect?","How can I reproduce it?","goes privately to Ernest","avoid passwords","sessionStorage","if(!response.ok)throw","Your note was not sent. It is still here","Received. Thank you"] )assert.match(page,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(page,/type="(?:file|email)"|rating|required[^>]*id="name"/i)});
