import { unavailable } from "../_shared/access.js";

function safe(value) {
  return /^[A-Za-z0-9._:-]{1,160}$/.test(String(value || "")) ? String(value) : "";
}

export async function onRequestGet({ request, env }) {
  if (env.ANALYTICS_DASHBOARD_ENABLED !== "true") return unavailable();
  const url = new URL(request.url);
  const hosts = new Set(String(env.ANALYTICS_OWNER_HOSTS || "").split(",").map(value => value.trim().toLowerCase()).filter(Boolean));
  if (!hosts.has(url.host.toLowerCase())) return unavailable();

  const config = {
    apiKey: safe(env.FIREBASE_API_KEY),
    authDomain: safe(env.FIREBASE_AUTH_DOMAIN),
    projectId: safe(env.FIREBASE_PROJECT_ID),
    appId: safe(env.FIREBASE_APP_ID),
  };
  const configured = Object.values(config).every(Boolean);
  const page = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow,noarchive">
  <title>My Lab - Trikzik Labs</title>
  <style>
    :root{color-scheme:dark;--ink:#f6f0df;--muted:#9fb0a8;--green:#38dc7e;--amber:#f3cb77;--pink:#ff9fc7;--blue:#8cbcff;--panel:#07110f;--line:#52645c}*{box-sizing:border-box}
    body{margin:0;background:radial-gradient(circle at 10% 0,#0b221a 0,transparent 34rem),#020807;color:var(--ink);font:16px/1.5 system-ui}main{width:min(1120px,calc(100% - 30px));margin:auto;padding:30px 0 54px}
    h1{color:var(--green);font-size:clamp(2.35rem,7vw,4.4rem);line-height:.92;margin:0}h2,h3,p{margin-top:0}.bar,.toolbar,.cards,.health,.tabs,.decision-actions,.confirm-actions,.meta{display:flex;gap:12px;flex-wrap:wrap}.bar{justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:20px}
    button,select,textarea{min-height:44px;padding:10px 12px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--ink);font:inherit}textarea{width:100%;min-height:100px;resize:vertical}button:not(:disabled){cursor:pointer}button:not(:disabled):hover,button:not(:disabled):focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{border-color:var(--green);outline:2px solid var(--green);outline-offset:2px}button:disabled,select:disabled,textarea:disabled{opacity:.45}
    .tabs{margin:18px 0}.tabs button{flex:1 1 180px;font-weight:750}.tabs button[aria-selected="true"]{border-color:var(--green);background:#0d2b1d;box-shadow:inset 0 -3px var(--green)}.view[hidden],.lab-card[hidden],#decision-confirm[hidden]{display:none}
    .notice{margin:16px 0;padding:12px;border:1px solid var(--amber);border-radius:8px;background:#1b1609;color:#f8df9d}.locked{padding:28px;border:1px dashed var(--line);border-radius:12px;text-align:center;color:var(--muted)}
    .lab-card{border:1px solid var(--line);border-radius:14px;background:linear-gradient(145deg,#0d1c18,#06100e);overflow:hidden}.project-head{display:flex;justify-content:space-between;align-items:start;gap:16px;padding:20px;border-bottom:1px solid #294038}.project-head h2{margin:0;color:var(--green);font-size:clamp(1.7rem,5vw,2.7rem)}.project-head a{display:inline-block;color:var(--ink);border:1px solid var(--green);border-radius:7px;padding:10px 13px;text-decoration:none;white-space:nowrap}.meta{margin-top:12px}.pill{border:1px solid var(--line);border-radius:999px;padding:4px 9px;color:var(--muted);font-size:.78rem}
    .lab-columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.lab-panel{padding:20px;min-width:0}.lab-panel+.lab-panel{border-left:1px solid #294038}.lab-panel h3{font-size:1.1rem;color:var(--blue)}.eyebrow{color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.11em}.lab-panel li{margin:.55rem 0}.prompt{padding:12px;border-left:3px solid var(--pink);background:#2a1420}.decision-actions button{flex:1 1 120px}.decision-actions [data-decision="approved"]{border-color:var(--green)}.decision-actions [data-decision="changes_requested"]{border-color:var(--pink)}.confirm{margin-top:12px;padding:12px;border:1px solid var(--amber);border-radius:9px;background:#1b1609}.confirm-actions button{flex:1 1 130px}.workflow{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.workflow div{padding:9px;border:1px solid #2b4139;border-radius:7px}.workflow strong{display:block;font-size:.84rem}.workflow span{display:block;color:var(--muted);font-size:.78rem}.delivery-warning{margin-top:12px;color:var(--amber);font-size:.86rem}.action-status{min-height:1.5em;margin:10px 0 0;color:var(--green)}
    .toolbar{align-items:end;margin:20px 0}.toolbar label{display:grid;gap:4px}.toolbar span{color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.1em}.health{margin:16px 0}.health div{flex:1 1 180px;padding:12px;border:1px solid var(--line);border-radius:8px;background:var(--panel)}.health strong{display:block;margin-top:3px}.cards{margin:18px 0}.card{flex:1 1 200px;text-align:left;padding:16px;border:1px solid var(--line);border-radius:10px;background:var(--panel)}.card strong{display:block;color:var(--green);font-size:2rem}.card small{display:block;color:var(--muted)}.card.active{border-color:var(--green);box-shadow:inset 3px 0 var(--green)}
    .table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:820px}th,td{text-align:left;padding:10px;border-bottom:1px solid #25342d}td:nth-child(n+3),th:nth-child(n+3){text-align:right}.empty{text-align:center!important;color:var(--muted);padding:28px}.muted{color:var(--muted)}#status{min-height:1.5em}.feedback{color:var(--green)}
    @media(max-width:820px){.lab-columns{grid-template-columns:1fr}.lab-panel+.lab-panel{border-left:0;border-top:1px solid #294038}}
    @media(max-width:650px){main{width:min(100% - 20px,1120px);padding-top:18px}.bar,.project-head{align-items:stretch;flex-direction:column}.bar button,.project-head a,.toolbar button,.toolbar select{width:100%}.tabs{position:sticky;top:0;z-index:4;background:#020807;padding:8px 0;margin:8px 0}.toolbar>*{flex:1 1 145px}.lab-panel,.project-head{padding:16px}.decision-actions button,.confirm-actions button{flex-basis:100%}.workflow{grid-template-columns:1fr}}
  </style>
</head>
<body>
<main>
  <div class="bar"><div><p class="muted">Private owner view</p><h1>My Lab</h1></div><div><button id="login">Sign in with Google</button> <button id="logout" hidden>Sign out</button></div></div>
  <p id="status" role="status" class="muted">${configured ? "Sign in to open My Lab." : "Firebase web configuration is not complete."}</p>
  <nav class="tabs" aria-label="Owner dashboard views"><button id="lab-tab" type="button" aria-selected="true" aria-controls="lab-view">My Lab</button><button id="signals-tab" type="button" aria-selected="false" aria-controls="signals-view">Signals</button></nav>
  <section class="view" id="lab-view" aria-labelledby="lab-tab">
    <div class="locked" id="lab-locked">Sign in with the verified owner account to load project work and saved decisions.</div>
    <article class="lab-card" id="lab-card" hidden>
      <header class="project-head"><div><p class="eyebrow">First complete workflow</p><h2 id="project-name">Project</h2><div class="meta"><span class="pill" id="project-commit">Revision</span><span class="pill" id="project-tests">Tests</span><span class="pill" id="project-evidence">Evidence</span></div></div><a id="project-preview" href="#" target="_blank" rel="noopener noreferrer">Open preview</a></header>
      <div class="lab-columns">
        <section class="lab-panel"><p class="eyebrow">Ready for you</p><h3 id="project-build-status">Owner review</h3><p id="project-latest"></p><ul id="review-checklist"></ul><p class="prompt" id="review-prompt"></p><ul id="feedback-prompts"></ul></section>
        <section class="lab-panel"><p class="eyebrow">Needs your say</p><h3 id="decision-question">Decision</h3><p><strong>Scope:</strong> <span id="decision-scope"></span></p><p><strong>Recommendation:</strong> <span id="decision-recommendation"></span></p><label for="decision-note" class="eyebrow">Optional note</label><textarea id="decision-note" maxlength="400" disabled placeholder="What should happen next?"></textarea>
          <div class="decision-actions" id="decision-actions"><button type="button" data-decision="approved" disabled>Approve direction</button><button type="button" data-decision="changes_requested" disabled>Request a change</button><button type="button" data-decision="parked" disabled>Park for now</button></div>
          <div class="confirm" id="decision-confirm" hidden><strong id="confirm-title">Review decision</strong><p id="confirm-copy"></p><p class="delivery-warning">Saving does not message or wake Pip, Rivet, Slack, or any agent.</p><div class="confirm-actions"><button type="button" id="confirm-save">Save to My Lab</button><button type="button" id="confirm-back">Back</button></div></div>
          <button type="button" id="reset-draft" disabled>Reset note</button><p id="lab-action-status" class="action-status" role="status"></p>
          <div class="workflow" aria-label="Decision delivery state"><div><strong>Saved</strong><span id="state-saved">Not saved</span></div><div><strong>Delivered</strong><span id="state-delivered">Not delivered</span></div><div><strong>Accepted</strong><span id="state-accepted">Not accepted</span></div><div><strong>Completed</strong><span id="state-completed">Not started</span></div></div><p class="delivery-warning" id="delivery-explanation"></p>
        </section>
        <section class="lab-panel"><p class="eyebrow">Underway</p><h3 id="project-lead">No linked run</h3><p><strong>Latest result</strong><br><span id="underway-result"></span></p><p><strong>Current blocker</strong><br><span id="underway-blocker"></span></p><p><strong>Evidence verified</strong><br><time id="underway-verified"></time></p><p class="notice">This dashboard can record an owner decision, but its delivery route is unverified. A saved decision remains waiting for manual delivery.</p></section>
      </div>
    </article>
  </section>
  <section class="view" id="signals-view" aria-labelledby="signals-tab" hidden>
    <p class="notice" id="context-notice">Context is shown after an authenticated query. Test fixtures and production counts are never mixed.</p>
    <section class="health" aria-label="Data health"><div><span class="eyebrow">Context</span><strong id="health-context">LOCKED</strong></div><div><span class="eyebrow">Collection</span><strong id="health-collection">OFF</strong></div><div><span class="eyebrow">Last event bucket</span><strong id="health-last">NONE</strong></div><div><span class="eyebrow">Query</span><strong id="health-query">WAITING</strong></div></section>
    <div class="toolbar" aria-label="Notebook controls"><label><span>Time window</span><select id="range" disabled><option value="24h">24 hours</option><option value="7d" selected>7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select></label><label><span>Experiment</span><select id="experiment-filter" disabled><option value="">All experiments</option></select></label><button id="refresh" type="button" disabled>Refresh notebook</button><button id="export" type="button" disabled>Export visible rows</button><button id="clear-filter" type="button" disabled>Show all event types</button></div>
    <section class="cards" aria-label="Metric filters"><button class="card" type="button" data-event="experiment_open" disabled><strong id="opens">-</strong>Experiment opens<small id="opens-compare">No prior comparison</small></button><button class="card" type="button" data-event="first_interaction" disabled><strong id="starts">-</strong>First interactions<small id="starts-compare">No prior comparison</small></button><button class="card" type="button" data-event="share" disabled><strong id="shares">-</strong>Replay shares<small id="shares-compare">No prior comparison</small></button><button class="card" type="button" data-event="support_click" disabled><strong id="support">-</strong>Support clicks<small id="support-compare">No prior comparison</small></button></section>
    <div class="table-wrap"><table><thead><tr><th>Experiment / event</th><th>Source / release</th><th>Current</th><th>Prior</th><th>Change</th></tr></thead><tbody id="rows"><tr><td class="empty" colspan="5">Sign in to query the test notebook.</td></tr></tbody></table></div>
  </section>
</main>
<script type="module">
  import{initializeApp}from"https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
  import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
  const cfg=${JSON.stringify(config)},ready=${configured},q=selector=>document.querySelector(selector);
  const status=q("#status"),contextNotice=q("#context-notice"),range=q("#range"),experimentFilter=q("#experiment-filter"),login=q("#login"),logout=q("#logout"),refresh=q("#refresh"),exportButton=q("#export"),clearFilter=q("#clear-filter"),rowsBody=q("#rows"),cards=[...document.querySelectorAll(".card")],decisionButtons=[...document.querySelectorAll("[data-decision]")],number=new Intl.NumberFormat();
  const labels={site:"Trikzik Labs",moon:"Moon Snail",star:"Starfall",dungeon:"Dungeon Reset",brain:"Brain in a Jar",scribble:"Scribble Engine",traffic:"Traffic With No Excuse",jelly:"Jelly Bench",mirror:"Mirror Mischief"};
  let auth,user,currentRows=[],priorRows=[],eventFilter=null,lastContext="test",generatedAt=null,comparisonStatus="unavailable",loadGeneration=0,activeLoadController=null,saveGeneration=0,activeSaveController=null,labData=null,pendingDecision=null,saveInFlight=false;
  function key(row){return[row.event,row.experiment,row.source,row.format,row.release].join("|")}
  function total(rows,event){return rows.filter(row=>row.event===event).reduce((sum,row)=>sum+row.total,0)}
  function comparison(event){if(comparisonStatus==="unavailable")return"Prior comparison unavailable";if(comparisonStatus==="partial")return"Partial prior period; comparison withheld";const current=total(currentRows,event),prior=total(priorRows,event),delta=current-prior;if(!current&&!prior)return"No change from prior period";if(!prior)return"+"+number.format(delta)+"; no prior events";const percent=Math.round(delta/prior*100);return(delta>=0?"+":"")+number.format(delta)+" ("+(percent>=0?"+":"")+percent+"%) vs prior"}
  function changeLabel(current,prior){if(comparisonStatus==="unavailable")return"Not comparable";if(comparisonStatus==="partial")return"Partial prior period";const delta=current-prior;if(!current&&!prior)return"0";if(!prior)return"+"+number.format(delta)+" / no prior";return(delta>=0?"+":"")+number.format(delta)+" ("+((delta/prior*100)>=0?"+":"")+Math.round(delta/prior*100)+"%)"}
  function setSignedIn(active){range.disabled=!active;experimentFilter.disabled=!active;refresh.disabled=!active;cards.forEach(card=>card.disabled=!active);q("#decision-note").disabled=!active;decisionButtons.forEach(button=>button.disabled=!active);q("#reset-draft").disabled=!active;if(!active){exportButton.disabled=true;clearFilter.disabled=true}}
  function visibleRows(){return currentRows.filter(row=>(!eventFilter||row.event===eventFilter)&&(!experimentFilter.value||row.experiment===experimentFilter.value))}
  function syncExperiments(){const selected=experimentFilter.value,values=[...new Set(currentRows.map(row=>row.experiment))].sort();experimentFilter.replaceChildren(new Option("All experiments",""),...values.map(value=>new Option(labels[value]||value,value)));if(values.includes(selected))experimentFilter.value=selected}
  function render(){
    const metricIds={experiment_open:["opens","opens-compare"],first_interaction:["starts","starts-compare"],share:["shares","shares-compare"],support_click:["support","support-compare"]};
    Object.entries(metricIds).forEach(([event,[valueId,compareId]])=>{q("#"+valueId).textContent=number.format(total(currentRows,event));q("#"+compareId).textContent=comparison(event)});cards.forEach(card=>{const active=card.dataset.event===eventFilter;card.classList.toggle("active",active);card.setAttribute("aria-pressed",String(active))});clearFilter.disabled=!eventFilter;const visible=visibleRows();exportButton.disabled=!visible.length;
    if(!visible.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=5;td.className="empty";td.textContent=currentRows.length?"No rows match these filters.":"No aggregate events in this window.";tr.append(td);rowsBody.replaceChildren(tr);return}const priorMap=new Map(priorRows.map(row=>[key(row),row.total]));rowsBody.replaceChildren(...visible.map(row=>{const prior=priorMap.get(key(row))||0,tr=document.createElement("tr"),values=[(labels[row.experiment]||row.experiment)+" / "+row.event.replaceAll("_"," "),row.source+" / "+row.release,number.format(row.total),number.format(prior),changeLabel(row.total,prior)];values.forEach(value=>{const td=document.createElement("td");td.textContent=value;tr.append(td)});return tr}))
  }
  function showView(name){const lab=name==="lab";q("#lab-view").hidden=!lab;q("#signals-view").hidden=lab;q("#lab-tab").setAttribute("aria-selected",String(lab));q("#signals-tab").setAttribute("aria-selected",String(!lab))}
  function decisionLabel(value){return({pending:"Not saved",approved:"Approved direction",changes_requested:"Change requested",parked:"Parked"})[value]||"Not saved"}
  function list(target,items){target.replaceChildren(...items.map(value=>{const item=document.createElement("li");item.textContent=value;return item}))}
  function clearLab(){labData=null;pendingDecision=null;q("#lab-locked").hidden=false;q("#lab-card").hidden=true;q("#decision-confirm").hidden=true;q("#decision-note").value="";q("#lab-action-status").textContent=""}
  function renderLab(data){labData=data;const project=data.project,workflow=data.workflow;q("#lab-locked").hidden=true;q("#lab-card").hidden=false;q("#project-name").textContent=project.name;q("#project-commit").textContent="Commit "+project.sourceRevision;q("#project-tests").textContent=project.testResult;q("#project-evidence").textContent="Desktop + phone checked";const preview=new URL(project.previewUrl);if(preview.protocol!=="https:"||!preview.hostname.endsWith(".ernest-turner.pages.dev"))throw new Error("Unsafe preview URL");q("#project-preview").href=preview.href;q("#project-build-status").textContent=project.buildStatus;q("#project-latest").textContent=project.latestResult;list(q("#review-checklist"),project.reviewChecklist);q("#review-prompt").textContent=project.reviewPrompt;list(q("#feedback-prompts"),project.feedbackPrompts);q("#decision-question").textContent=project.decisionQuestion;q("#decision-scope").textContent=project.scope;q("#decision-recommendation").textContent=project.recommendation;q("#decision-note").value=workflow.note;q("#state-saved").textContent=decisionLabel(workflow.decision)+(workflow.savedAt?" · "+new Date(workflow.savedAt).toLocaleString():"");q("#state-delivered").textContent="Waiting for delivery";q("#state-accepted").textContent="Not accepted";q("#state-completed").textContent="Not started";q("#delivery-explanation").textContent=data.delivery.explanation;q("#project-lead").textContent=project.lead;q("#underway-result").textContent=project.latestResult;q("#underway-blocker").textContent=project.blocker;q("#underway-verified").dateTime=project.evidenceVerifiedAt;q("#underway-verified").textContent=new Date(project.evidenceVerifiedAt).toLocaleString();pendingDecision=null;q("#decision-confirm").hidden=true;decisionButtons.forEach(button=>button.disabled=!user||saveInFlight);q("#reset-draft").disabled=!user||saveInFlight}
  function beginDecision(value){if(!labData||saveInFlight)return;pendingDecision=value;q("#confirm-title").textContent=decisionLabel(value);q("#confirm-copy").textContent="Save this owner decision for "+labData.project.name+" at revision "+labData.project.sourceRevision+"?";q("#decision-confirm").hidden=false;q("#lab-action-status").textContent="Review the exact decision, then save or go back.";q("#confirm-save").focus()}
  function cancelSave(){saveGeneration+=1;if(activeSaveController)activeSaveController.abort();activeSaveController=null;saveInFlight=false}
  async function request(path,requestUser,signal,options={}){const token=await requestUser.getIdToken();if(signal.aborted||user!==requestUser)throw new DOMException("Stale owner request","AbortError");const headers={...(options.headers||{}),Authorization:"Bearer "+token};return fetch(path,{...options,headers,signal})}
  async function api(path,requestUser,signal){const response=await request(path,requestUser,signal);if(!response.ok)throw new Error(String(response.status));return response.json()}
  async function saveDecision(){const requestUser=user,decision=pendingDecision;if(!requestUser||!labData||!decision||saveInFlight)return;cancelSave();saveInFlight=true;const generation=++saveGeneration,controller=new AbortController();activeSaveController=controller;const current=()=>generation===saveGeneration&&!controller.signal.aborted&&user===requestUser;decisionButtons.forEach(button=>button.disabled=true);q("#confirm-save").disabled=true;q("#confirm-back").disabled=true;q("#reset-draft").disabled=true;q("#lab-action-status").textContent="Saving in My Lab…";const body={project:"scribble",decision,note:q("#decision-note").value,expectedRevision:labData.workflow.revision,requestId:crypto.randomUUID()};try{const response=await request("/owner/api/lab",requestUser,controller.signal,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!current())return;if(response.status===409){renderLab(data);q("#lab-action-status").textContent="A newer saved decision was loaded. Review it before trying again.";return}if(!response.ok)throw new Error(String(response.status));renderLab(data);q("#lab-action-status").textContent=data.repeated?"This decision was already saved. It is still waiting for delivery.":"Saved in My Lab. It is waiting for delivery."}catch(error){if(!current()||error?.name==="AbortError")return;q("#lab-action-status").textContent="Save failed. Your draft is still here; try again when ready."}finally{if(current()){activeSaveController=null;saveInFlight=false;q("#confirm-save").disabled=false;q("#confirm-back").disabled=false;decisionButtons.forEach(button=>button.disabled=false);q("#reset-draft").disabled=false}}}
  function cancelLoad(){loadGeneration+=1;if(activeLoadController)activeLoadController.abort();activeLoadController=null}
  function clearNotebook(){currentRows=[];priorRows=[];eventFilter=null;lastContext="test";generatedAt=null;comparisonStatus="unavailable";experimentFilter.value="";syncExperiments();render();q("#health-context").textContent="LOCKED";q("#health-collection").textContent="OFF";q("#health-last").textContent="NONE";q("#health-query").textContent="WAITING"}
  async function load(){const requestUser=user;if(!requestUser)return;cancelLoad();const generation=++loadGeneration,controller=new AbortController();activeLoadController=controller;const current=()=>generation===loadGeneration&&!controller.signal.aborted&&user===requestUser;status.className="muted";status.textContent="Refreshing My Lab.";refresh.disabled=true;exportButton.disabled=true;q("#health-query").textContent="RUNNING";try{const who=await api("/owner/api/whoami",requestUser,controller.signal);if(!current())return;if(!who.pinned){cancelLoad();setSignedIn(false);status.textContent="Verified UID: "+who.uid+". Pin this exact UID as FIREBASE_OWNER_UID before owner access.";return}const lab=await api("/owner/api/lab",requestUser,controller.signal);if(!current())return;renderLab(lab);status.className="feedback";status.textContent="My Lab loaded. Saved decisions remain waiting for delivery.";try{const data=await api("/owner/api/analytics?range="+encodeURIComponent(range.value),requestUser,controller.signal);if(!current())return;currentRows=data.current.rows;priorRows=data.prior.rows;lastContext=data.context;generatedAt=data.generatedAt;comparisonStatus=data.comparison?.status||"unavailable";syncExperiments();contextNotice.textContent=data.health.syntheticTestData?"TEST NOTEBOOK - labeled fixtures only. This is not live visitor traffic.":"PRODUCTION NOTEBOOK - aggregate public interaction counts only; no visitor or session identities.";q("#health-context").textContent=data.context.toUpperCase();q("#health-collection").textContent=data.health.collectionEnabled?"ON":"OFF";q("#health-last").textContent=data.health.lastEventAt?new Date(data.health.lastEventAt).toLocaleString():"NONE";q("#health-query").textContent="OK";render()}catch(error){if(!current()||error?.name==="AbortError")return;q("#health-query").textContent="ERROR";contextNotice.textContent="Signals are unavailable. My Lab decisions remain separate."}}catch(error){if(!current()||error?.name==="AbortError")return;q("#health-query").textContent="ERROR";status.className="muted";status.textContent="My Lab request failed. Authentication or the preview database is unavailable."}finally{if(current()){activeLoadController=null;refresh.disabled=false}}}
  q("#lab-tab").addEventListener("click",()=>showView("lab"));q("#signals-tab").addEventListener("click",()=>showView("signals"));decisionButtons.forEach(button=>button.addEventListener("click",()=>beginDecision(button.dataset.decision)));q("#confirm-save").addEventListener("click",saveDecision);q("#confirm-back").addEventListener("click",()=>{pendingDecision=null;q("#decision-confirm").hidden=true;q("#lab-action-status").textContent="Nothing saved. Your note is still here."});q("#reset-draft").addEventListener("click",()=>{if(!labData)return;q("#decision-note").value=labData.workflow.note;pendingDecision=null;q("#decision-confirm").hidden=true;q("#lab-action-status").textContent="Draft reset. No decision was changed."});
  cards.forEach(card=>card.addEventListener("click",()=>{eventFilter=eventFilter===card.dataset.event?null:card.dataset.event;render();status.textContent=eventFilter?"Filtered to "+card.childNodes[1].textContent.trim()+".":"Showing all event types."}));clearFilter.addEventListener("click",()=>{eventFilter=null;render();status.textContent="Showing all event types."});experimentFilter.addEventListener("change",()=>{render();status.textContent=experimentFilter.value?"Filtered to "+(labels[experimentFilter.value]||experimentFilter.value)+".":"Showing all experiments."});refresh.addEventListener("click",load);range.addEventListener("change",load);
  function csvCell(value){let text=String(value??"");if(/^[\\t\\r\\n ]*[=+\\-@]/.test(text))text="'"+text;return'"'+text.replaceAll('"','""')+'"'}
  exportButton.addEventListener("click",()=>{if(!user||!generatedAt)return;const visible=visibleRows();if(!visible.length)return;const priorMap=new Map(priorRows.map(row=>[key(row),row.total])),cells=[["experiment","event","source","format","release","current_count","prior_count","generated_at"],...visible.map(row=>[row.experiment,row.event,row.source,row.format,row.release,row.total,priorMap.get(key(row))||0,generatedAt])],csv=cells.map(line=>line.map(csvCell).join(",")).join("\\r\\n"),href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=href;anchor.download="trikzik-"+lastContext+"-analytics.csv";anchor.click();setTimeout(()=>URL.revokeObjectURL(href),0);status.textContent="Exported "+visible.length+" visible aggregate rows."});
  if(ready){auth=getAuth(initializeApp(cfg));login.onclick=async()=>{status.textContent="Opening Google sign-in.";try{await signInWithPopup(auth,new GoogleAuthProvider())}catch{status.textContent="Google sign-in could not start. Reload and try again."}};logout.onclick=()=>{cancelLoad();cancelSave();user=null;login.hidden=false;logout.hidden=true;setSignedIn(false);clearNotebook();clearLab();status.textContent="Sign in to open My Lab.";signOut(auth).catch(()=>{status.textContent="Local dashboard locked. Reload to retry Firebase sign-out."})};onAuthStateChanged(auth,value=>{cancelLoad();cancelSave();user=value;login.hidden=!!value;logout.hidden=!value;setSignedIn(Boolean(value));clearNotebook();clearLab();if(value)load();else status.textContent="Sign in to open My Lab."})}else login.disabled=true;
</script>
</body></html>`;
  return new Response(page, { headers: {
    "cache-control": "private, no-store",
    "content-security-policy": "default-src 'none'; script-src 'unsafe-inline' https://www.gstatic.com https://apis.google.com; style-src 'unsafe-inline'; connect-src 'self' https://*.googleapis.com https://*.firebaseapp.com; frame-src https://accounts.google.com https://trikzik-owner-auth.firebaseapp.com; img-src 'self' data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
    "content-type": "text/html; charset=utf-8",
    "referrer-policy": "no-referrer",
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY",
  }});
}

export function onRequest() {
  return new Response("Method not allowed", { status: 405, headers: { "cache-control": "no-store" } });
}
