const EVENT_NAMES=new Set(["specimen_select","experiment_open","first_interaction","export","share","support_click"]);
const EXPERIMENTS=new Set(["site","moon","star","dungeon","brain","scribble","traffic","jelly","mirror"]);
const SOURCES=new Set(["selector","game","footer"]);
const FORMATS=new Set(["none","png","svg","setup","replay"]);
const RELEASE="analytics-v2";
const MAX_BODY_BYTES=1024,WINDOW_SECONDS=60,GLOBAL_LIMIT=12;
function response(status){return new Response(status===204?null:status===404?"Not found":"Request rejected",{status,headers:{"cache-control":"no-store","content-type":"text/plain; charset=utf-8","x-content-type-options":"nosniff"}});}
function configuration(enabled){return new Response(JSON.stringify({enabled,release:RELEASE}),{status:200,headers:{"cache-control":"no-store","content-type":"application/json; charset=utf-8","x-content-type-options":"nosniff"}});}
function origins(env){return new Set(String(env.ANALYTICS_ALLOWED_ORIGINS||"").split(",").map(v=>v.trim()).filter(Boolean));}
function valid(v,context){if(!v||typeof v!=="object"||Array.isArray(v))return false;const expected=["context","event","experiment","format","release","source"];if(Object.keys(v).sort().join()!==expected.join())return false;if(!EVENT_NAMES.has(v.event)||!EXPERIMENTS.has(v.experiment)||!SOURCES.has(v.source)||!FORMATS.has(v.format)||v.context!==context||v.release!==RELEASE)return false;if((v.event==="export")!==(["png","svg","setup"].includes(v.format)))return false;if((v.event==="share")!==(v.format==="replay"))return false;if(v.event==="support_click"&&(v.experiment!=="site"||v.source!=="footer"))return false;if(["specimen_select","experiment_open","first_interaction"].includes(v.event)&&v.experiment==="site")return false;return true;}
export function onRequestGet({request,env}){const requestOrigin=new URL(request.url).origin;if(!origins(env).has(requestOrigin))return response(404);return configuration(env.ANALYTICS_ENABLED==="true"&&Boolean(env.TRIKZIK_DB?.prepare));}
export async function onRequestPost({request,env}){if(env.ANALYTICS_ENABLED!=="true"||!env.TRIKZIK_DB?.prepare)return response(404);const origin=request.headers.get("origin");if(!origin||!origins(env).has(origin))return response(403);if(request.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase()!=="application/json")return response(415);if(Number(request.headers.get("content-length")||0)>MAX_BODY_BYTES)return response(413);const text=await request.text();if(new TextEncoder().encode(text).byteLength>MAX_BODY_BYTES)return response(413);let payload;try{payload=JSON.parse(text);}catch{return response(400);}const context=String(env.ANALYTICS_CONTEXT||"");if(!valid(payload,context))return response(400);const now=Math.floor(Date.now()/1000),windowStart=now-(now%WINDOW_SECONDS);const quota=await env.TRIKZIK_DB.prepare("INSERT INTO ingest_windows(window_start,count) VALUES(?,1) ON CONFLICT(window_start) DO UPDATE SET count=count+1 WHERE count < ? RETURNING count").bind(windowStart,GLOBAL_LIMIT).first();if(!quota)return response(429);const bucketStart=now-(now%300);await env.TRIKZIK_DB.prepare("INSERT INTO analytics_events(bucket_start,context,event,experiment,source,format,release,count) VALUES(?,?,?,?,?,?,?,1) ON CONFLICT(bucket_start,context,event,experiment,source,format,release) DO UPDATE SET count=count+1").bind(bucketStart,context,payload.event,payload.experiment,payload.source,payload.format,payload.release).run();return response(204);}
export function onRequest(){return response(405);}
