const MAX_BODY_BYTES=8192,WINDOW_SECONDS=60,GLOBAL_LIMIT=20;
const LIMITS=Object.freeze({message:2000,name:80,page:120,happened:1000,expected:1000,reproduction:1500});
function json(status,value){return new Response(JSON.stringify(value),{status,headers:{"cache-control":"no-store","content-type":"application/json; charset=utf-8","referrer-policy":"no-referrer","x-content-type-options":"nosniff"}})}
function enabled(env){return env.ANALYTICS_QUERY_CONTEXT==="test"&&Boolean(env.TRIKZIK_DB?.prepare)}
function sameOrigin(request){const url=new URL(request.url),origin=request.headers.get("origin");return origin===url.origin&&request.headers.get("sec-fetch-site")==="same-origin"}
function clean(value,key,required=false){if(typeof value!=="string"||value.length>LIMITS[key]||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value))return null;const result=value.trim();return required&&!result?null:result}
function validBody(value){if(!value||typeof value!=="object"||Array.isArray(value))return null;const keys=["expected","happened","message","name","page","reproduction","requestId"];if(Object.keys(value).sort().join()!==keys.join())return null;if(typeof value.requestId!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value.requestId))return null;const body={requestId:value.requestId};for(const key of Object.keys(LIMITS)){const result=clean(value[key],key,key==="message");if(result===null)return null;body[key]=result}return body}
function accepted(row,repeated){return json(200,{accepted:true,confirmation:String(row.feedback_id||"").slice(0,36),receivedAt:new Date(Number(row.created_at)*1000).toISOString(),repeated})}
export async function onRequestPost({request,env}){if(!enabled(env))return json(404,{error:"Not found"});if(!sameOrigin(request))return json(403,{error:"Request rejected"});if(request.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase()!=="application/json")return json(415,{error:"Request rejected"});if(Number(request.headers.get("content-length")||0)>MAX_BODY_BYTES)return json(413,{error:"Request rejected"});const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)return json(413,{error:"Request rejected"});let value;try{value=JSON.parse(raw)}catch{return json(400,{error:"Request rejected"})}const body=validBody(value);if(!body)return json(400,{error:"Request rejected"});try{const existing=await env.TRIKZIK_DB.prepare("SELECT feedback_id,created_at FROM owner_feedback WHERE request_id=? LIMIT 1").bind(body.requestId).first();if(existing)return accepted(existing,true);if(typeof env.TRIKZIK_DB.batch!=="function")return json(503,{error:"Feedback is unavailable"});const now=Math.floor(Date.now()/1000),windowStart=now-(now%WINDOW_SECONDS),feedbackId=crypto.randomUUID(),quota=env.TRIKZIK_DB.prepare("INSERT INTO feedback_ingest_windows(window_start,count) VALUES(?,1) ON CONFLICT(window_start) DO UPDATE SET count=count+1 WHERE count < ? RETURNING count").bind(windowStart,GLOBAL_LIMIT),insert=env.TRIKZIK_DB.prepare("INSERT INTO owner_feedback(feedback_id,request_id,message,name,page,happened,expected,reproduction,context,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(request_id) DO NOTHING RETURNING feedback_id,created_at").bind(feedbackId,body.requestId,body.message,body.name,body.page,body.happened,body.expected,body.reproduction,"test",now);const [quotaResult,insertResult]=await env.TRIKZIK_DB.batch([quota,insert]);if(!quotaResult?.results?.[0])return json(429,{error:"Please try again later"});const saved=insertResult?.results?.[0];if(saved)return accepted(saved,false);const repeated=await env.TRIKZIK_DB.prepare("SELECT feedback_id,created_at FROM owner_feedback WHERE request_id=? LIMIT 1").bind(body.requestId).first();return repeated?accepted(repeated,true):json(503,{error:"Feedback is unavailable"})}catch{return json(503,{error:"Feedback is unavailable"})}}
export function onRequest(){return json(405,{error:"Method not allowed"})}
export { validBody };
