const CERT_URL = "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com";
const CERT_CACHE_MS = 60 * 60 * 1000;
let certificateCache = { expiresAt: 0, fetchedAt: 0, values: null };
function json(status, message) { return new Response(JSON.stringify({ error: message }), { status, headers: { "cache-control":"private, no-store","content-type":"application/json; charset=utf-8","referrer-policy":"no-referrer","x-content-type-options":"nosniff" } }); }
function decodePart(value) { if(!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error("Invalid token"); const n=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"="); return Uint8Array.from(atob(n),c=>c.charCodeAt(0)); }
function parsePart(value){return JSON.parse(new TextDecoder().decode(decodePart(value)));}
async function certificates(fetchImpl,force=false){const now=Date.now();if(!force&&certificateCache.values&&certificateCache.expiresAt>now)return certificateCache.values;if(force&&certificateCache.values&&now-certificateCache.fetchedAt<60000)return certificateCache.values;const r=await fetchImpl(CERT_URL,{headers:{accept:"application/json"}});if(!r.ok)throw new Error("Certificates unavailable");const payload=await r.json(),values=Array.isArray(payload?.keys)?payload.keys:[];if(!values.length)throw new Error("Certificates invalid");certificateCache={values,fetchedAt:now,expiresAt:now+CERT_CACHE_MS};return values;}
export async function verifyFirebaseIdToken(token,env,fetchImpl=fetch){const projectId=String(env.FIREBASE_PROJECT_ID||"").trim(),raw=String(token||"");if(!/^[a-z0-9-]{6,30}$/.test(projectId))throw new Error("Firebase is not configured");if(raw.length<16||raw.length>4096)throw new Error("Invalid token");const parts=raw.split(".");if(parts.length!==3)throw new Error("Invalid token");const [h,c,s]=parts,header=parsePart(h),claims=parsePart(c);if(header.alg!=="RS256"||typeof header.kid!=="string")throw new Error("Unsupported token");const match=keys=>keys.find(key=>key.kid===header.kid&&key.kty==="RSA"&&key.alg==="RS256");let jwk=match(await certificates(fetchImpl));if(!jwk)jwk=match(await certificates(fetchImpl,true));if(!jwk)throw new Error("Signing key unavailable");const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,decodePart(s),new TextEncoder().encode(`${h}.${c}`)))throw new Error("Invalid signature");const now=Math.floor(Date.now()/1000);if(claims.aud!==projectId||claims.iss!==`https://securetoken.google.com/${projectId}`)throw new Error("Invalid claims");if(!Number.isFinite(claims.exp)||claims.exp<=now-30||!Number.isFinite(claims.iat)||claims.iat>now+30||!Number.isFinite(claims.auth_time)||claims.auth_time>now+30)throw new Error("Invalid time claims");if(typeof claims.sub!=="string"||!claims.sub||claims.sub.length>128||claims.user_id!==claims.sub)throw new Error("Invalid uid");if(claims.email_verified!==true||typeof claims.email!=="string"||!claims.email.trim())throw new Error("Verified email required");return claims;}
function bearer(request){return request.headers.get("authorization")?.match(/^Bearer ([A-Za-z0-9_.-]+)$/)?.[1]||"";}
export async function requireOwner(request,env,{allowUnpinned=false,fetchImpl=fetch}={}){const ownerUid=String(env.FIREBASE_OWNER_UID||"").trim(),ownerEmail=String(env.FIREBASE_OWNER_EMAIL||"").trim().toLowerCase();if(!ownerEmail||(!allowUnpinned&&!ownerUid))return{ok:false,response:unavailable()};try{const claims=await verifyFirebaseIdToken(bearer(request),env,fetchImpl);if(claims.email.trim().toLowerCase()!==ownerEmail)throw new Error("Owner email mismatch");if(!allowUnpinned&&claims.sub!==ownerUid)throw new Error("Owner uid mismatch");return{ok:true,claims};}catch{return{ok:false,response:json(401,"Owner authentication required")};}}
export function sameOriginApiRequest(request,env){const url=new URL(request.url),hosts=new Set(String(env.ANALYTICS_OWNER_HOSTS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean)),origin=request.headers.get("origin");return hosts.has(url.host.toLowerCase())&&(!origin||origin===url.origin)&&request.headers.get("sec-fetch-site")==="same-origin";}
export function unavailable(){return json(404,"Not found");}
